/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.patron.creacional.factory.view;

import ec.edu.ups.patron.creacional.factory.controller.VehiculoFactory;
import ec.edu.ups.patron.creacional.factory.model.Vehiculo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author charl
 */
public class FormularioVehiculo extends JFrame {

    private JComboBox<String> comboTipoVehiculo;
    private JTextField txtPlaca;
    private JTextField txtCilindraje;
    private JTextField txtAvaluo;
    private JTextField txtImpuesto;
    private List<Vehiculo> vehiculos;

    public FormularioVehiculo(List<Vehiculo> vehiculos) {
        this.vehiculos = vehiculos;

        setTitle("Añadir Vehículo");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Centrar la ventana
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        JLabel lblTipoVehiculo = new JLabel("Tipo de Vehículo:");
        String[] tipos = {"auto", "camioneta", "camion"};
        comboTipoVehiculo = new JComboBox<>(tipos);
        panel.add(lblTipoVehiculo);
        panel.add(comboTipoVehiculo);
        JLabel lblPlaca = new JLabel("Ingrese la Placa:");
        txtPlaca = new JTextField(20);
        panel.add(lblPlaca);
        panel.add(txtPlaca);
        JLabel lblCilindraje = new JLabel("Ingrese el Cilindraje:");
        txtCilindraje = new JTextField(20);
        panel.add(lblCilindraje);
        panel.add(txtCilindraje);
        JLabel lblAvaluo = new JLabel("Ingrese el Avaluo:");
        txtAvaluo = new JTextField(20);
        panel.add(lblAvaluo);
        panel.add(txtAvaluo);
        JLabel lblImpuesto = new JLabel("Ingrese el Porcentaje Impuesto a la Propiedad:");
        txtImpuesto = new JTextField(20);
        panel.add(lblImpuesto);
        panel.add(txtImpuesto);
        JButton btnGuardar = new JButton("Guardar");
        btnGuardar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                guardarVehiculo();
            }
        });
        panel.add(btnGuardar);
        add(panel);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarVehiculo() {
        try {
            // Obtener datos del formulario
            String tipoVehiculo = (String) comboTipoVehiculo.getSelectedItem();
            String placa = txtPlaca.getText();
            int cilindraje = Integer.parseInt(txtCilindraje.getText());
            double avaluo = Double.parseDouble(txtAvaluo.getText());
            double impuesto = Double.parseDouble(txtImpuesto.getText());

            VehiculoFactory vehiculoFactory = new VehiculoFactory();
            Vehiculo vehiculo = vehiculoFactory.crearVehiculoFactory(tipoVehiculo);
            vehiculo.setPlaca(placa);
            vehiculo.setCilindraje(cilindraje);
            vehiculo.setAvaluo(avaluo);
            vehiculo.setImpuesto(impuesto);
            vehiculos.add(vehiculo);
            JOptionPane.showMessageDialog(this, "Vehículo guardado con éxito");
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores válidos para los campos numéricos");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
