/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.patron.creacional.factory.view;

import ec.edu.ups.patron.creacional.factory.model.Vehiculo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author charl
 */
public class MenuVehiculo extends JFrame {

    private List<Vehiculo> vehiculos;
    
    public MenuVehiculo() {
        
        vehiculos = new ArrayList<>();
        setTitle("Menú de Vehículos");
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centrar la ventana
        JPanel panel = new JPanel();
        JButton btnAddVehiculo = new JButton("Añadir Vehículo");
        JButton btnShowVehiculo = new JButton("Mostrar Vehículo");
        JButton btnSalir = new JButton("Salir");

        btnAddVehiculo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new FormularioVehiculo(vehiculos);
            }
        });

        btnShowVehiculo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                
                new ListarVehiculo(vehiculos);
            }
        });

        btnSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        panel.add(btnAddVehiculo);
        panel.add(btnShowVehiculo);
        panel.add(btnSalir);
        add(panel);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new MenuVehiculo();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
